#!/bin/bash
#
##############################################################################
#                                                                            #
#                     Pi-Star M17 preview                                    #
#                                                                            #
#     Version 1.0, Code, Design and Development by Alessio Caiazza (IU5BON)  #
#                                                                            #
##############################################################################
# Install with
# curl https://raw.githubusercontent.com/USA-RedDragon/Pi-Star_Binaries_sbin/M17/pistar-install-m17 | sudo bash -

set -e

# Make sure we are root, if we cant stop the services, the results are a bit hit and miss.
if [ "$(id -u)" != "0" ]; then
  echo -e "You need to be root to run this command...\n"
  exit 1
fi

# Make the disk RW
mount -o remount,rw /

git config --global --add safe.directory /var/www/dashboard
pushd /var/www/dashboard
if [[ $(git remote | grep  USARedDragon) != "USARedDragon" ]] ; then
    echo "Patching Dashboard"
    
    git remote add USARedDragon https://github.com/USA-RedDragon/Pi-Star_DV_Dash.git
    git fetch USARedDragon
    git checkout M17
fi
popd

pushd /usr/local/sbin
if [[ $(git remote | grep  USARedDragon) != "USARedDragon" ]] ; then
    echo "Patching sbin"
    
    git remote add USARedDragon https://github.com/USA-RedDragon/Pi-Star_Binaries_sbin.git
    git fetch USARedDragon
    git checkout M17
fi
popd

pushd /usr/local/bin
if [[ $(git remote | grep  USARedDragon) != "USARedDragon" ]] ; then
    echo "Patching bin"

    git remote add USARedDragon https://github.com/USA-RedDragon/Pi-Star_v4_Binaries_bin.git
    git fetch USARedDragon
    git checkout M17
fi
popd

pistar-firewall
touch /etc/m17gateway
m17gateway.service install

if [[ ! -d /usr/local/etc/M17_Audio ]]; then
    echo "Downloading M17 Voice Files..."
    mkdir /usr/local/etc/M17_Audio
    curl --fail -o /usr/local/etc/M17_Audio/de_DE.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/de_DE.m17
    curl --fail -o /usr/local/etc/M17_Audio/de_DE.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/de_DE.indx
    curl --fail -o /usr/local/etc/M17_Audio/dk_DK.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/dk_DK.m17
    curl --fail -o /usr/local/etc/M17_Audio/dk_DK.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/dk_DK.indx
    curl --fail -o /usr/local/etc/M17_Audio/en_GB.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/en_GB.m17
    curl --fail -o /usr/local/etc/M17_Audio/en_GB.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/en_GB.indx
    curl --fail -o /usr/local/etc/M17_Audio/en_US.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/en_US.m17
    curl --fail -o /usr/local/etc/M17_Audio/en_US.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/en_US.indx
    curl --fail -o /usr/local/etc/M17_Audio/es_ES.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/es_ES.m17
    curl --fail -o /usr/local/etc/M17_Audio/es_ES.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/es_ES.indx
    curl --fail -o /usr/local/etc/M17_Audio/fr_FR.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/fr_FR.m17
    curl --fail -o /usr/local/etc/M17_Audio/fr_FR.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/fr_FR.indx
    curl --fail -o /usr/local/etc/M17_Audio/it_IT.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/it_IT.m17
    curl --fail -o /usr/local/etc/M17_Audio/it_IT.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/it_IT.indx
    curl --fail -o /usr/local/etc/M17_Audio/pl_PL.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/pl_PL.m17
    curl --fail -o /usr/local/etc/M17_Audio/pl_PL.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/pl_PL.indx
    curl --fail -o /usr/local/etc/M17_Audio/se_SE.m17 -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/se_SE.m17
    curl --fail -o /usr/local/etc/M17_Audio/se_SE.indx -s https://raw.githubusercontent.com/g4klx/M17Gateway/master/Audio/se_SE.indx
    echo "Done"
fi

sync
mount -o remount,ro /

echo "M17 is now available on your system, please make sure your MMDVM FW is >= 1.6.0, and you enabled M17 mode from the web interface"
